language: ada

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gnat-7

script:
- gnatmake hello.adb
- /usr/bin/time ./hello

after_script:
- du -sch *
- ldd hello
